### ISSUE TITLE
Godot 3 Support?

### ISSUE THREAD

**Issue by smks** [Pennycook/godot-utility-ai#3]
Hi is this easily portable to Godot 3?

**Comment by Pennycook** [comment]
It should be possible, but I don't know how easy it would be.  The code takes advantage of some new GDScript features introduced in Godot 4 (like lambda functions) and so there are a few places where porting would require more than simple syntax changes (e.g., replacing `@export` with `export`).

I'm using Godot 4 for my own projects, so I have no plans to port this to Godot 3 myself.  But if you (or anybody else reading this) wants to try, I'd definitely be open to having a Godot 3 branch in the repository.
