### ISSUE TITLE
Compile Error Upon Install

### ISSUE THREAD

**Issue by dfego** [Pennycook/godot-utility-ai#4]
I just tried to install this asset from the asset library, and see the following errors when it loads:
```
  res://addons/utility_ai/core/utility_ai_option.gd:70 - Parse Error: Invalid constructor "Object()", use "Object.new()" instead.
  res://addons/utility_ai/core/utility_ai.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/utility_ai/core/utility_ai.gd" with error "Parse error". (User)
  ```
Godot v4.2.1.stable.official [b09f793f5]

I reproduced this on a completely empty project just now.

**Comment by Pennycook** [comment]
Thanks for reporting this.  This seems to be new behavior in Godot 4.2, resulting from https://github.com/godotengine/godot/pull/75988.
