### ISSUE TITLE
How to use it in c#?

### ISSUE THREAD

**Issue by NetCodersX** [Pennycook/godot-utility-ai#5]
### Feature Description

How to use it in c#?

### Contribution Request

No

**Comment by Pennycook** [comment]
@LeonFretter ported the plugin to C# (see https://github.com/LeonFretter/godot-utility-ai-cs) and it's available in the Asset  Library too (https://godotengine.org/asset-library/asset/2110).

I'm not at all familiar with the C# version of Godot, and I have no plans to support it myself.  I'd be open to contributions if somebody could figure out how to make the GDScript and C# versions coexist in one place, but I'm not sure that's possible.
